language: java
jdk:
- openjdk8

addons:
    apt:
        packages:
            - ant 
    sonarcloud:
        organization: simonesinceri
        token: ef1888c771ec52da6e36077c4c4d7a142af5cd93
        
script:
    - ant build
    - sonar-scanner
