language: java
jdk:
- openjdk8

addons:
    apt:
        packages:
            - ant 
    sonarcloud:
        organization: simonesinceri
        token: 23e3e8e5a32633f02eb788d98fd7f55dc85ac9e0
        
script:
    - ant build
    - sonar-scanner
