dist: xenial
language: java
jdk:
- openjdk8

addons:
    apt:
        packages:
            - ant 
    sonarcloud:
        organization: simonesinceri
        token: 75fb849a75d9fe94801be7be21fcb88f077e44b8
script:
    - ant build
    - sonar-scanner
