language: java
jdk:
- openjdk8

addons:
    apt:
        packages:
            - ant 
    sonarcloud:
        organization: simonesinceri
        token: bef81524fc1b8e8ba4e1fb1e5d483b0252416306
script:
    - ant build
    - sonar-scanner
